(elpaca tmux-mode)
(elpaca orderless)
(elpaca base16-theme)
(elpaca vertico)
(elpaca gcmh)
(elpaca undo-fu)
(elpaca meow)
(elpaca kdl-mode)
(elpaca nix-ts-mode)
(elpaca colorful-mode)
(elpaca eat)
(elpaca company)
(elpaca company-qml)
(elpaca-wait)

(provide 'init-packages)
